/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Satelite(props) {
  const { nodes, materials } = useGLTF("/satelite2.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="toppannel"
        position={[0.039, 0.251, 0.029]}
        rotation={[0, -0.892, -Math.PI / 2]}
        scale={[0.521, 0.015, 0.244]}
      >
        <mesh
          name="Cube013"
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials.toppannel}
        />
        <mesh
          name="Cube013_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials.body}
        />
        <mesh
          name="Cube013_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube013_2.geometry}
          material={materials.rode}
        />
        <mesh
          name="Cube013_3"
          castShadow
          receiveShadow
          geometry={nodes.Cube013_3.geometry}
          material={materials.pannels}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/satelite2.glb");
